[package]
name = "oak"
description = "A logging library"
version = "0.1.0"
authors = ["Lance Hart <me@lancehart>"]
edition = "2021"
repository = "https://github.com/shipsimfan/oak.git"
license = "GPL-3.0-or-later"
publish = false

[dependencies]
time.git = "https://github.com/shipsimfan/lib-time"
